### ISSUE TITLE
Could add an example of uploading files?

### ISSUE THREAD

**Issue by zwl1619** [hammerframework/hammer#10]
Could add an example of uploading files?
such as adding images in an article, or uploading an avatar,or something like that.

**Comment by cannikin** [comment]
Yes, we'll have an image uploader in the https://github.com/hammerframework/example-blog project soon!

**Comment by cannikin** [comment]
Hello! We've got image uploading in our example blog. We're using https://filestack.com for uploads since they give you a really nice uploader and you don't have to provision storage anywhere. You get 100 uploads per month for free.

If you take a look at our [usage](https://github.com/hammerframework/example-blog/blob/master/web/src/components/Admin/PostForm/PostForm.js) it's pretty simple: initialize their widget and attach it a DOM element on your page (lines 98-114). There are tons of [options](https://filestack.github.io/filestack-js/interfaces/pickeroptions.html) for the picker.

Our custom behavior is that if the user already has an image attached to a blog post then we display that (line 116) and hide the uploader (line 113), along with a button to replace the existing image (lines 121-127) which just shows the picker again. Whether the image is set or not is kept in local component state (lines 21, 33, 39).

Once the upload is complete we take the URL given to us by Filestack and add that to state so that the image appears in place of the picker, and then on submit we append that URL to the object containing the rest of the data in the form (line 26).

Let us know how that looks and if it was anything like you were expecting! :)

**Comment by cannikin** [comment]
We're really focusing on making Hammer great for the JAMstack, which means you won't have any server to save images to! But, Hammer is still using regular ol' React so anything that works for React will work here as well. For example: https://www.signet.hr/file-upload-with-node-react/

**Comment by santoshgistto** [comment]
@cannikin  is possible to link firebase storage ?

**Comment by cannikin** [comment]
Hi @santoshgistto I'm not familiar with firebase storage, could you tell me more about it? If they have an API then you should be able to pull it in and display in a Redwood app!

**Comment by santoshgistto** [comment]
@cannikin  yes they are having apis 

Firebase provides admin sdk
**Capabilities:**   may  be suitable fo redwood 
1. Authentication : https://firebase.google.com/docs/reference/admin/node/admin.auth 
2. firestore  : https://firebase.google.com/docs/reference/admin/node/admin.firestore
3. storage  https://firebase.google.com/docs/storage/admin/start 
4. firebase extensions  : This will helpful when image gets uploaded for generating thumbnail  https://firebase.google.com/products/extensions/storage-resize-images
5. Web push notification : would be helpful if running static page needs refresh.

**Comment by cannikin** [comment]
Have you seen the [File Uploads](https://redwoodjs.com/cookbook/file-uploads) cookbook recipe? That might give you a starting point to try integrating Firebase storage!
